name: "Create GitHub Issue"
description: "Creates a GitHub issue"
inputs:
  token:
    description: "GitHub access token"
    required: true
    default: ""
  action-id:
    description: "GitHub Action ID"
    required: true
    default: ""
  title:
    description: "Title of the issue"
    required: true
    default: "Title"
  artifact:
    description: "Name of the artifact"
    required: true
    default: "Something like buildpack-ubuntu2004-d12f0d12c9f69baa7b825033b2f9c89acea738bf1ae734efa4b343833f897e1d"
  package-name:
    description: "Name of the package being released"
    required: true
    default: "Something like buildpack-ubuntu2004"
  package-version:
    description: "Version of the package being released"
    required: true
    default: "Something like 1.0.0"
outputs:
  issue-id:
    description: "ID of the created issue on GitHub"
runs:
  using: "node12"
  main: "dist/index.js"
