name: "Add comment to current PR"
description: "Adds a comment to current PR"
inputs:
  token:
    description: "GitHub access token"
    required: true
    default: ""
  comment:
    description: "Comment body"
    required: true
    default: ""
runs:
  using: "node12"
  main: "dist/index.js"
