name: "Add comment to current PR"
description: "Adds a comment to current PR"
inputs:
  token:
    description: "GitHub access token"
    required: true
    default: ""
  action-id:
    description: "GitHub Action ID"
    required: true
    default: ""
  artifact:
    description: "Name of the artifact"
    required: true
    default: "Something like buildpack-ubuntu2004-d12f0d12c9f69baa7b825033b2f9c89acea738bf1ae734efa4b343833f897e1d"
runs:
  using: "node12"
  main: "dist/index.js"
