name: "Checks whether a PR is buildpack related"
description: "Checks whether a PR is buildpack related"
inputs:
  token:
    description: "GitHub access token"
    required: true
    default: ""
runs:
  using: "node12"
  main: "dist/index.js"

