name: "Checks whether a PR is buildpack related"
description: "Checks whether a PR is buildpack related"
inputs:
  token:
    description: "GitHub access token"
    required: true
    default: ""
  label:
    description: "Label to check for"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
