name: buildpack:ubuntu2004

on:
  pull_request:
    paths:
      - '.github/workflows/buildpack-ubuntu2004.yml'
      - 'scripts/docker/buildpack/Dockerfile.ubuntu2004'
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_DOCKER_REPOSITORY: docker.pkg.github.com/${{ github.repository }}
      IMAGE_NAME: buildpack
      IMAGE_VARIANT: ubuntu2004

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build scripts/docker/${IMAGE_NAME} --file scripts/docker/${IMAGE_NAME}/Dockerfile.$IMAGE_VARIANT --tag $IMAGE_NAME

      - name: Test image
        run: |
          docker run -v ${PWD}:/tmp -e CI=1 $IMAGE_NAME /tmp/scripts/build.sh

      - name: Push image
        run: |
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin

          VERSION=$(docker inspect --format={{.Config.Labels.version}} $IMAGE_NAME)
          docker tag $IMAGE_NAME $GITHUB_DOCKER_REPOSITORY/$IMAGE_NAME-$IMAGE_VARIANT:$VERSION
          (docker pull -a $GITHUB_DOCKER_REPOSITORY/$IMAGE_NAME-$IMAGE_VARIANT | awk '{ print $1 }' | grep "${VERSION}:") > /dev/null
          R=$?
          if [ $R -eq 0 ]
          then
            echo ""
            echo "Error: Version ${VERSION} already exist for $GITHUB_DOCKER_REPOSITORY/$IMAGE_NAME-$IMAGE_VARIANT. Aborting."
            echo ""
            docker logout
            false
          fi
          docker push $GITHUB_DOCKER_REPOSITORY/$IMAGE_NAME-$IMAGE_VARIANT:$VERSION

          docker tag $IMAGE_NAME $GITHUB_DOCKER_REPOSITORY/$IMAGE_NAME-$IMAGE_VARIANT:latest
          docker push $GITHUB_DOCKER_REPOSITORY/$IMAGE_NAME-$IMAGE_VARIANT:latest

          docker logout
