name: buildpack-deps:ubuntu1804

on:
  pull_request:
    paths:
      - '.github/workflows/buildpack-deps-ubuntu1804.yml'
      - 'scripts/docker/buildpack-deps/Dockerfile.ubuntu1804'

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_REPOSITORY: docker.pkg.github.com/${{ github.repository }}
      MAKE_JOBS: 4
      IMAGE_NAME: buildpack-deps
      IMAGE_VARIANT: ubuntu1804

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Upgrade ${{ env.IMAGE_NAME }}-${{ env.IMAGE_VARIANT }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u "${GITHUB_ACTOR}" --password-stdin
          scripts/ci/docker_upgrade.sh ${{ env.IMAGE_NAME }} ${{ env.IMAGE_VARIANT }} ${{ env.DOCKER_REPOSITORY }}
          docker logout docker.pkg.github.com

      - name: comment PR
        uses: aarlt/comment-on-pr@v1.2.0
        with:
          msg:  "`${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_REPO_DIGEST }}`."
          check_for_duplicate_msg: false  # OPTIONAL
