name: buildpack:ubuntu2004

on:
  pull_request:
    paths:
      - '.github/workflows/buildpack-ubuntu2004.yml'
      - 'scripts/docker/buildpack/Dockerfile.ubuntu2004'
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_DOCKER_REPOSITORY: docker.pkg.github.com/${{ github.repository }}
      IMAGE_NAME: buildpack
      IMAGE_VARIANT: ubuntu2004
      ARCHIVE: ${{ env.ARCHIVE }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build scripts/docker/${IMAGE_NAME} --file scripts/docker/${IMAGE_NAME}/Dockerfile.$IMAGE_VARIANT --tag $IMAGE_NAME

#      - name: Test image
#        run: |
#          docker run -v ${PWD}:/tmp -e CI=1 $IMAGE_NAME /tmp/scripts/build.sh

      - name: Save image
        run: |
          VERSION=$(docker inspect --format={{.Config.Labels.version}} $IMAGE_NAME)
          docker save -o $IMAGE_NAME-$IMAGE_VARIANT.tar $IMAGE_NAME
          HASH=$(sha256sum $IMAGE_NAME-$IMAGE_VARIANT.tar | awk '{print $1}')
          mv $IMAGE_NAME-$IMAGE_VARIANT.tar $HOME/$IMAGE_NAME-$IMAGE_VARIANT-$VERSION-$HASH.tar
          echo "::set-env name=VERSION::$VERSION"
          echo "::set-env name=HASH::$HASH"
          echo "::set-env name=ARCHIVE::$HOME/$IMAGE_NAME-$IMAGE_VARIANT-$VERSION-$HASH.tar"

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: $ARCHIVE
          path: $ARCHIVE
