name: buildpack:create

on:
  issues:
    types: [labeled]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_DOCKER_REPOSITORY: docker.pkg.github.com/${{ github.repository }}
      IMAGE_NAME: buildpack
      IMAGE_VARIANT: emscripten

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare action
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build action
        run: npm i && npm run build
        working-directory: ./.github/actions/buildpack-pr-check

      - name: Create buildpack comment on PR
        uses: ./.github/actions/buildpack-pr-check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

#      - name: Push image
#        run: |
#          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_ACTOR} --password-stdin
#
#          EMSDK_VERSION=$(grep "emscripten/emsdk" scripts/docker/buildpack/Dockerfile.emscripten | cut -f 2 -d ' ' | cut -f 2 -d ':')
#          VERSION=$(docker inspect --format={{.Config.Labels.version}} $IMAGE_NAME)
#          docker tag $IMAGE_NAME $GITHUB_DOCKER_REPOSITORY/$IMAGE_NAME-$IMAGE_VARIANT-$EMSDK_VERSION:$VERSION
#          docker push $GITHUB_DOCKER_REPOSITORY/$IMAGE_NAME-$IMAGE_VARIANT-$EMSDK_VERSION:$VERSION
#
#          docker tag $IMAGE_NAME $GITHUB_DOCKER_REPOSITORY/$IMAGE_NAME-$IMAGE_VARIANT-$EMSDK_VERSION:latest
#          docker push $GITHUB_DOCKER_REPOSITORY/$IMAGE_NAME-$IMAGE_VARIANT-$EMSDK_VERSION:latest
#
#          docker logout
