name: buildpack:ubuntu2004

on:
  pull_request:
    paths:
      - '.github/workflows/buildpack-ubuntu2004.yml'
      - 'scripts/docker/buildpack/Dockerfile.ubuntu2004'
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_REPOSITORY: docker.pkg.github.com/${{ github.repository }}
      IMAGE_NAME: buildpack
      IMAGE_VARIANT: ubuntu2004

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Upgrade ${{ env.IMAGE_NAME }}-${{ env.IMAGE_VARIANT }}
        run: |
          echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u "${GITHUB_ACTOR}" --password-stdin
          scripts/ci/docker_upgrade.sh
          docker logout docker.pkg.github.com

      - name: comment PR
        uses: unsplash/comment-on-pr@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg:  "`${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_REPO_DIGEST }}`."
          check_for_duplicate_msg: false  # OPTIONAL
